on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install graphviz_support dependencies
        run: |
          sudo apt install graphviz
          pip install extensions/graphviz_support
      - name: Run graphviz_support tests
        run: |
          python -m extensions.graphviz_support.graphviz_support.tests.test_lg_graphviz_api